// Drizzle schema. Grows one slice at a time.
//
// Architecture rule: every tenant-owned table carries `organization_id` and every
// query is org-scoped.
//
// The auth and tenancy tables (user, session, account, verification, organization,
// member, invitation) are owned by Better Auth and generated by its CLI — regenerate
// with `pnpm --filter @pod-dex/api auth:generate` rather than editing by hand.
export * from "./auth-schema.js";
export * from "./app-schema.js";
